// Dutch source strings are translation keys; no user-provided text is translated.
export const ENGLISH = Object.freeze({
  "Afname": "Import",
  "Teruglevering": "Export",
  "Afname en teruglevering": "Import and export",
  "Geen": "None",
  "Doorgetrokken": "Solid",
  "Gestreept": "Dashed",
  "Gestippeld": "Dotted",
  "Losse kwartieren": "Individual intervals",
  "Eén aaneengesloten blok": "One continuous block",
  "Blokken met minimale duur": "Blocks with minimum duration",
  "Prijsentity afname": "Import price entity",
  "Prijsentity teruglevering": "Export price entity",
  "Correctie op terugleverprijs": "Export price correction",
  "Grafiek": "Graph",
  "Actuele prijzen": "Current prices",
  "Titel": "Title",
  "Titel tonen": "Show title",
  "Verticale hoverlijn": "Vertical hover line",
  "Gemiddelde prijslijn": "Average price line",
  "Prijsgrenzen tonen": "Show price thresholds",
  "Lijnstijl": "Line style",
  "Lijndikte": "Line width",
  "Vaste lijnkleur": "Fixed line color",
  "Vulling onder lijn": "Fill below line",
  "Vulkleur": "Fill color",
  "Vulling vervagen": "Fade fill",
  "Selectiemethode": "Selection method",
  "Minimale blokduur": "Minimum block duration",
  "Gunstige perioden": "Favorable periods",
  "Lijn en vulling": "Line and fill",
  "Prijskleuren": "Price colors",
  "Goedkope prijs": "Cheap price",
  "Normale prijs": "Normal price",
  "Dure prijs": "Expensive price",
  "Prijs rond nul": "Price around zero",
  "Negatieve prijs": "Negative price",
  "Kleur gunstige afnameperioden": "Favorable import period color",
  "Kleur gunstige terugleverperioden": "Favorable export period color",
  "Goedkoop": "Cheap",
  "Normaal": "Normal",
  "Duur": "Duration",
  "Goedkoopste uren per dag": "Cheapest hours per day",
  "Beste terugleveruren per dag": "Best export hours per day",
  "Tabel goedkoopste momenten": "Cheapest periods table",
  "Tabel beste teruglevermomenten": "Best export periods table",
  "Morgenprijzen tonen vanaf": "Show tomorrow's prices from",
  "Algemeen": "General",
  "uur": "h",
  "Een prijsentity voor afname is verplicht.": "An import price entity is required.",
  "Prijsniveaus moeten oplopen: goedkoop < normaal < duur.": "Price thresholds must increase: cheap < normal < expensive.",
  "Afname-entiteit niet gevonden": "Import entity not found",
  "Terugleverbron ontbreekt": "Export source missing",
  "Stel export_entity in, of kies alleen afname.": "Set export_entity, or select import only.",
  "Teruglever-entiteit niet gevonden": "Export entity not found",
  "Nog geen prijsgegevens": "No price data yet",
  "De afname-entiteit bevat geen prijsintervallen voor vandaag.": "The import entity has no price intervals for today.",
  "Nu": "Now",
  "nu": "now",
  "Gem. afname": "Avg. import",
  "Gem. teruglevering": "Avg. export",
  "Vandaag": "Today",
  "Morgen": "Tomorrow",
  "prijsinterval ontbreekt": "price interval missing",
  "prijsintervallen ontbreken": "price intervals missing",
  "Morgenprijzen ontbreken": "Tomorrow's prices are missing",
  "Morgenprijzen zijn onvolledig": "Tomorrow's prices are incomplete",
  "Legenda": "Legend",
  "Elektriciteitsprijzen per interval. Gebruik de pijltjestoetsen om prijzen te bekijken.": "Electricity prices per interval. Use the arrow keys to inspect prices.",
  "Goedkoopst": "Cheapest",
  "Beste opbrengst": "Best return",
  "onbekend": "unknown",
  "Toon": "Show",
  "Verberg": "Hide",
  "Gunstige momenten": "Favorable periods",
  "Dag": "Day",
  "Moment": "Tariff",
  "Start": "Start",
  "Einde": "End",
  "goedkoopste": "cheapest",
  "beste": "best",
  "afname": "import",
  "teruglevering": "export",
  "niet beschikbaar": "unavailable",
  "cent per kilowattuur": "cents per kilowatt-hour",
  "tot": "to",
  "Dynamische energieprijzen": "Dynamic energy prices",
  "Afname- en terugleverprijzen met gunstige momenten per dag.": "Import and export prices with favorable periods per day.",
  "Kies welke tarieven in de gedeelde tijdgrafiek staan.": "Choose which tariffs appear in the shared time chart.",
  "Staat los van de gekozen grafiekweergave.": "Independent of the selected graph mode.",
  "Verberg de titel om actieve gunstige-urencontext op die plek te tonen.": "Hide the title to show active favorable-hours context in its place.",
  "Toont een verticale hulplijn bij het actieve prijsinterval.": "Shows a vertical guide for the active price interval.",
  "Toont per zichtbare tariefreeks een gelabeld gemiddelde.": "Shows a labeled average for each visible tariff series.",
  "Toont de lijnen en prijslabels voor goedkoop, normaal en duur.": "Shows the cheap, normal and expensive threshold lines and price labels.",
  "Kies doorgetrokken, gestreept of gestippeld.": "Choose solid, dashed or dotted.",
  "Lijndikte van 1 tot 8 pixels.": "Line thickness from 1 to 8 pixels.",
  "Optioneel. Leeg behoudt de automatische prijskleuren.": "Optional. Empty keeps automatic price colors.",
  "Toont een transparante kleur onder de afnamelijn.": "Shows a transparent fill below the import line.",
  "Optioneel. Leeg gebruikt de primaire Home Assistant-kleur.": "Optional. Empty uses the Home Assistant primary color.",
  "Laat de vulling geleidelijk transparant worden naar de onderkant.": "Gradually fades the fill towards the bottom.",
  "Kies losse kwartieren, één blok of meerdere blokken.": "Choose individual intervals, one block or multiple blocks.",
  "Alleen gebruikt bij blokken met minimale duur.": "Only used for blocks with minimum duration.",
  "Toont een transparante kleur onder de terugleverlijn.": "Shows a transparent fill below the export line.",
  "Optioneel. Leeg gebruikt blauw.": "Optional. Empty uses blue.",
  "Optioneel. Leeg behoudt de groene themakleur voor gunstige prijzen.": "Optional. Empty keeps the theme's green color for favorable prices.",
  "Optioneel. Leeg behoudt de standaard oranje prijskleur.": "Optional. Empty keeps the default orange price color.",
  "Optioneel. Leeg behoudt de rode themakleur voor ongunstige prijzen.": "Optional. Empty keeps the theme's red color for unfavorable prices.",
  "Optioneel. Leeg behoudt de standaard kleur rond nul in de afnamegradiënt.": "Optional. Empty keeps the default zero-price color in the import gradient.",
  "Optioneel. Leeg behoudt de standaard negatieve afnameprijskleur.": "Optional. Empty keeps the default negative import price color.",
  "Optioneel, onafhankelijk van prijskleuren. Leeg behoudt de groene themakleur voor perioden, labels en tabel.": "Optional, independent of price colors. Empty keeps the theme's green color for periods, labels and table.",
  "Optioneel, onafhankelijk van prijskleuren. Leeg behoudt blauw voor perioden, labels en tabel.": "Optional, independent of price colors. Empty keeps blue for periods, labels and table.",
  "Onder deze prijs is afname goedkoop; voor teruglevering is laag juist ongunstig.": "Below this price import is cheap; for export low prices are unfavorable.",
  "Middelste prijsgrens voor beide tarieven.": "Middle price threshold for both tariffs.",
  "Boven deze prijs is afname duur en teruglevering gunstig.": "Above this price import is expensive and export is favorable.",
  "0 schakelt de selectie van goedkope afname-uren uit.": "0 disables cheap import hour selection.",
  "Toont aaneengesloten goedkope afnamemomenten onder de grafiek.": "Shows continuous cheap import periods below the chart.",
  "Prijsbron voor teruglevering. Verplicht zodra teruglevering wordt getoond.": "Export price source. Required whenever export is shown.",
  "Terugleverprijs = prijs uit terugleverentity + verschil. Negatieve waarden zijn toegestaan.": "Export price = export entity price + correction. Negative values are allowed.",
  "0 schakelt de selectie van beste terugleveruren uit.": "0 disables best export hour selection.",
  "Toont aaneengesloten beste teruglevermomenten onder de grafiek.": "Shows continuous best export periods below the chart.",
  "Vanaf dit uur worden beschikbare morgenprijzen getoond.": "Available tomorrow prices are shown from this hour.",
  "Controleer {entity} in de cardconfiguratie.": "Check {entity} in the card configuration.",
  "Goedkoopste {hours} uur/dag": "Cheapest {hours} h/day",
  "Beste teruglevering {hours} uur/dag": "Best export {hours} h/day",
  "Huidige {tariff}prijs {price}": "Current {tariff} price {price}",
  "{hours} u {minutes} min": "{hours} h {minutes} min",
  "{hours} uur": "{hours} h"
});

export function resolveLanguage(hass) {
  const language = hass?.locale?.language ?? hass?.language;
  return typeof language === 'string' && /^nl(?:[-_]|$)/i.test(language) ? 'nl' : 'en';
}

// getConfigForm has no hass argument in HA. Schema getters read the frontend root;
// native computeLabel/computeHelper are invoked as methods of hui-form-editor.
export function frontendHass() {
  return typeof document === 'undefined' ? undefined : document.querySelector('home-assistant')?.hass;
}

export function translate(text, language = 'en', values = {}) {
  const template = language === 'nl' ? text : ENGLISH[text] ?? text;
  return template.replace(/\{(\w+)\}/g, (_, key) => String(values[key] ?? `{${key}}`));
}

export function formatDuration(minutes, language = 'en') {
  const hours = Math.floor(minutes / 60);
  const remainder = minutes % 60;
  return hours && remainder ? translate('{hours} u {minutes} min', language, { hours, minutes: remainder })
    : hours ? translate('{hours} uur', language, { hours }) : `${remainder} min`;
}
